# This workflow is to apply CI/CD to create Azure App services (App services) which runs
# on VM; Do not use this workflow for container app
name: Build and deploy Python app to Azure Web App (lion)

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: lion
  PYTHON_VSN: '3.12'
  AZURE_RESOURCE_GROUP: rg-lion-app
  WEBSITES_CONTAINER_START_TIME_LIMIT: 188
  WEBSITES_ENABLE_APP_SERVICE_STORAGE: false
  WEBSITES_PORT: 8000
  FLASK_ENV: production
  LION_AZURE_APP_VERSION: ${{ vars.LION_AZURE_APP_VERSION }} # e.g., 0.1.0 which is set in GitHub Repo Settings > Environment Variables

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VSN }}

      # - name: Install dependencies
      - name: Activating virtual env antenv
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip setuptools
          echo antenv/bin/python --version
          echo "============================================================="

      - name: Install dependencies and package
        run: |
          source antenv/bin/activate
          pip install --upgrade pip setuptools

          pip install .
          pip show $AZURE_WEBAPP_NAME
          echo "$AZURE_WEBAPP_NAME installed; skipping app import due to missing env vars."
          echo "============================================================="
          echo "üìÅ Current directory contents:"
          ls -alh
          echo "============================================================="

      # - name: Create wheel distribution
      #   run: |
      #     source antenv/bin/activate
      #     python -m pip install --upgrade build wheel
      #     python -m build --wheel
      #     echo "============================================================="

      # - name: Upload artifact for deployment
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ${{ env.AZURE_WEBAPP_NAME }}
      #     path: |
      #       .
      #       dist/
      #       !antenv/

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
          path: |
            src/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    env:
      AZURE_SQL_USER: ${{ secrets.AZURE_SQL_USER }}
      AZURE_SQL_PASS: ${{ secrets.AZURE_SQL_PASS }}
      AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
      AZURE_SQL_DB: ${{ secrets.AZURE_SQL_DB }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
      AZURE_LION_APP_TENANT_ID: ${{ secrets.AZURE_LION_APP_TENANT_ID }}
      AZURE_LION_APP_CLIENT_ID: ${{ secrets.AZURE_LION_APP_CLIENT_ID }}
      AZURE_LION_APP_OBJECT_ID: ${{ secrets.AZURE_LION_APP_OBJECT_ID }}
      AZURE_LION_APP_CLIENT_SECRET: ${{ secrets.AZURE_LION_APP_CLIENT_SECRET }}
      FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      LION_APP: lion.lion_app:app

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5B026A751B2C41CB904E28DFBE0BF0A7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D1EA8B0CB0A6452EB61D86EC2166F59A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0F366397AB794420AE9F78492E6DFA18 }}

      - name: Disable Oryx
        run: |
          az webapp config appsettings set \
            --name "$AZURE_WEBAPP_NAME" \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --settings WEBSITES_DISABLE_ORYX=true SCM_DO_BUILD_DURING_DEPLOYMENT=false

      # Dynamically set Azure App Settings before deployment
      - name: Configure Azure App Settings
        run: |
          echo "Configuring Azure App Settings..."
          az webapp config appsettings set \
            --name "$AZURE_WEBAPP_NAME" \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --settings \
              SCM_DO_BUILD_DURING_DEPLOYMENT=false \
              WEBSITES_DISABLE_ORYX=true \
              AZURE_SQL_USER="$AZURE_SQL_USER" \
              AZURE_SQL_PASS="$AZURE_SQL_PASS" \
              AZURE_SQL_SERVER="$AZURE_SQL_SERVER" \
              AZURE_SQL_DB="$AZURE_SQL_DB" \
              AZURE_SUBSCRIPTION_ID="$AZURE_SUBSCRIPTION_ID" \
              AZURE_RESOURCE_GROUP="$AZURE_RESOURCE_GROUP" \
              AZURE_SUBSCRIPTION="$AZURE_SUBSCRIPTION" \
              AZURE_LION_APP_TENANT_ID="$AZURE_LION_APP_TENANT_ID" \
              AZURE_LION_APP_CLIENT_ID="$AZURE_LION_APP_CLIENT_ID" \
              AZURE_LION_APP_OBJECT_ID="$AZURE_LION_APP_OBJECT_ID" \
              AZURE_LION_APP_CLIENT_SECRET="$AZURE_LION_APP_CLIENT_SECRET" \
              FLASK_ENV="$FLASK_ENV" \
              FLASK_SECRET_KEY="$FLASK_SECRET_KEY" \
              WEBSITES_CONTAINER_START_TIME_LIMIT="$WEBSITES_CONTAINER_START_TIME_LIMIT" \
              AZURE_STORAGE_CONNECTION_STRING="$AZURE_STORAGE_CONNECTION_STRING" \
              WEBSITES_ENABLE_APP_SERVICE_STORAGE="$WEBSITES_ENABLE_APP_SERVICE_STORAGE" \
              WEBSITES_PORT="$WEBSITES_PORT" \
              PORT="$WEBSITES_PORT"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'

      - name: Set startup command with package installation
        run: |
          az webapp config set --name $AZURE_WEBAPP_NAME --resource-group $AZURE_RESOURCE_GROUP \
          --startup-file "gunicorn -w 4 -b 0.0.0.0:$WEBSITES_PORT $LION_APP"

      # - name: Set startup command with package installation
      #   run: |
      #     az webapp config set --name $AZURE_WEBAPP_NAME --resource-group $AZURE_RESOURCE_GROUP \
      #     --startup-file "pip uninstall lion && pip install dist/lion-$LION_AZURE_APP_VERSION-py3-none-any.whl && gunicorn -w 4 -b 0.0.0.0:$WEBSITES_PORT $LION_APP"

      - name: Verify startup command
        run: |
          az webapp config show \
            --name "$AZURE_WEBAPP_NAME" \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --query siteConfig.appCommandLine
